Setting UI
EntyR/RandomNumberDB pull request #10
Opened 2022-03-01 08:27 UTC by EntyR

2022-03-01 13:32 UTC, AlexeyKolosov commented on app/src/main/res/values/strings.xml
> +    <string name="number_not_even">Number isn\'t even</string>
why not use "Number is odd"?

2022-03-01 13:32 UTC, AlexeyKolosov commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
remove if it is not used

2022-03-01 13:36 UTC, EntyR commented on app/src/main/res/values/strings.xml
> +    <string name="number_not_even">Number isn\'t even</string>
I forgot this word, done

2022-03-01 13:36 UTC, EntyR commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
done

2022-03-01 13:37 UTC, AlexeyKolosov commented on app/src/main/res/drawable/rounded_button_shape_selector.xml
> +        <shape xmlns:android="http://schemas.android.com/apk/res/android">
copy-paste: no need to copy namespace to children elements

2022-03-01 13:57 UTC, AlexeyKolosov commented
Please .gitignore the whole .idea folder by adding .idea into .gitignore

2022-03-02 07:45 UTC, AlexeyKolosov requested changes

2022-03-02 07:45 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/di/AppModule.kt
>      }
also please declare its Dao as single too. see [example](https://aish05.medium.com/mvvm-koin-and-architecture-components-in-kotlin-6251100e2285)

2022-03-02 10:52 UTC, EntyR commented on app/src/main/res/drawable/rounded_button_shape_selector.xml
> +        <shape xmlns:android="http://schemas.android.com/apk/res/android">
done

2022-03-02 11:43 UTC, AlexeyKolosov requested changes

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/build.gradle
> +//    kapt "android.arch.persistence.room:compiler:1.1.1"
please remove commented code

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/RandomNumbersList.kt
> +
Please remove such big spaces in code

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/res/drawable/rounded_button_shape_selector.xml
> +            <solid android:color="@color/teal_200"/>
please check that colors match Figma

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/res/layout/fragment_random_numbers_list.xml
> +        app:backgroundTint="@color/teal_200"
please check color

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/res/layout/random_number_list_item.xml
> +        android:textColor="@drawable/rounded_button_text_color_selector"
please also add android:textStyle to make sure that it is bold

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/adapters/NumberListAdapter.kt
> +        holder.binding.btItemValue.text = currentList[position].number.toString()
according to design, it should be in the format of "Number X" please use string resource 
` <string name="list_item_number_text">Number %1$s</string>` and `getString(R.string.list_item_number_text, 55)`

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/res/layout/fragment_random_numbers_list.xml
> +        android:layout_marginTop="80dp"
please make this list scrollable under device bezels (remove margin and fix)

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/res/layout/random_number_list_item.xml
> +        android:layout_marginStart="32dp"
too big margin

2022-03-02 11:43 UTC, AlexeyKolosov commented on app/src/main/res/layout/random_number_list_item.xml
> +        android:layout_marginEnd="32dp"
too big margin

2022-03-02 11:44 UTC, AlexeyKolosov commented
Also, please add all margins and so on into `values/dimens.xml`

2022-03-02 11:57 UTC, AlexeyKolosov commented on app/src/main/res/values/colors.xml
> +    <color name="pale_yellow">#6DE4CE00</color>
Where did you get this color? I see in Figma that it should be #FFEDAB

2022-03-02 12:59 UTC, EntyR commented on app/src/main/res/layout/fragment_random_numbers_list.xml
> +        app:backgroundTint="@color/teal_200"
done

2022-03-02 12:59 UTC, EntyR commented on app/src/main/res/drawable/rounded_button_shape_selector.xml
> +            <solid android:color="@color/teal_200"/>
done

2022-03-02 12:59 UTC, EntyR commented on app/src/main/res/layout/random_number_list_item.xml
> +        android:textColor="@drawable/rounded_button_text_color_selector"
done

2022-03-02 12:59 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/adapters/NumberListAdapter.kt
> +        holder.binding.btItemValue.text = currentList[position].number.toString()
done

2022-03-02 13:08 UTC, EntyR commented on app/src/main/res/values/colors.xml
> +    <color name="pale_yellow">#6DE4CE00</color>
pick one that looks same, already changed

2022-03-02 13:09 UTC, EntyR commented on app/src/main/res/layout/random_number_list_item.xml
> +        android:layout_marginEnd="32dp"
done

2022-03-02 13:10 UTC, EntyR commented on app/src/main/res/layout/random_number_list_item.xml
> +        android:layout_marginStart="32dp"
done

2022-03-02 13:10 UTC, EntyR commented on app/src/main/res/layout/fragment_random_numbers_list.xml
> +        android:layout_marginTop="80dp"
done

2022-03-02 13:10 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/RandomNumbersList.kt
> +
done

2022-03-02 13:28 UTC, EntyR commented on app/build.gradle
> +//    kapt "android.arch.persistence.room:compiler:1.1.1"
done

2022-03-03 06:49 UTC, AlexeyKolosov requested changes

2022-03-03 06:49 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/MainActivity.kt
> +        setContentView(binding.root)
not sure that this line should be after if-block, because there is a chance that if-block may produce null pointer exception

2022-03-03 10:24 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/ui/MainActivity.kt
> +        setContentView(binding.root)
done

2022-03-03 11:13 UTC, AlexeyKolosov approved these changes

2022-03-03 11:13 UTC, merged