Update data and domain layer
EntyR/RandomNumberDB pull request #35
Opened 2022-03-18 14:02 UTC by EntyR

2022-03-19 12:39 UTC, AlexeyKolosov requested changes

2022-03-19 12:39 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/db/FluctuationDataBase.kt
> +abstract class FluctuationDataBase : RoomDatabase() {
lets use our existing database, just one per application

2022-03-19 12:39 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +        sensorManager.registerListener(
lets use `callbackFlow` here [https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/callback-flow.html](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/callback-flow.html)  as you can register listener directly in the flow body, and unregister there, using `awaitClose { ......unregister(listener) }`

2022-03-19 12:43 UTC, AlexeyKolosov commented
Please start with the implementation of a foreground service. It has its own lifecycle, so you can subscribe to sensor data flow right in service.onCreate(). The subscription will exist while service is not killed by the system. And if a callback flow is used, it will automatically unregister listener in case if service is destroyed

2022-03-19 12:46 UTC, AlexeyKolosov commented
As for gravity data format, it is enough to have only absolute value of acceleration of gravity, you don't need to use previous value in the formula.

2022-03-21 09:20 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +        sensorManager.registerListener(
done

2022-03-21 13:23 UTC, AlexeyKolosov requested changes

2022-03-21 13:23 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/services/CensorService.kt
> +class CensorService(
typo? Sensor

2022-03-21 13:23 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/services/CensorService.kt
> +    fun startGravityCensorObserving() = lifecycleScope.launch(Dispatchers.Default) {
please add `onCreate()` function, and subscribe to sensor data inside on create

2022-03-21 13:23 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/services/CensorService.kt
> +    inner class CensorServiceBinder : Binder() {
lets don't use bind-service at all in this task

2022-03-21 13:23 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/dao/IFluctuationDao.kt
> +    suspend fun addGravityFluctuationsRecord(records: List<FluctuationEntity>)
please make sure that you are not creating the new item in the table, please keep only one row, and edit it (add records/ replace records)

2022-03-21 13:23 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +                        value[0],
maybe vector?

2022-03-21 13:23 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +        val list: MutableList<GravityValue> = mutableListOf()
you don't need to keep all list here, just emit regular event as soon as possible

2022-03-21 13:23 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +                    trySend(list)
I think, trySend(gravValue) is enough, as the purpose of this flow if to provide regular values, not to store them

2022-03-21 13:23 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/dao/IFluctuationDao.kt
> +interface IFluctuationDao {
please don't forget to add this to DI

2022-03-21 13:23 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/repository/GravityFluctuationsRepository.kt
> +    override suspend fun saveRecordSessionData() {
lets implement this method with parameters such as data: List<..>, we will call this method from the service.

2022-03-21 13:27 UTC, AlexeyKolosov commented on domain/src/main/java/com/harman/roomdbapp/domain/model/GravityValue.kt
> +        return abs(x) + abs(y) + abs(z)
please use the length of a gravity vector, which is given by:
`sqrt(x.pow(2) + y.pow(2) + x.pow(2))`

2022-03-22 06:51 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/services/SensorService.kt
> +        startGravityCensorObserving()
```
gravitySensorDataSource.getSensorFlow().asLiveData().observe(this){ data ->

    lifecycleScope.launch(backgroundDispatcher){
             .... save to database here ...
    }
}

2022-03-22 06:51 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/services/SensorService.kt
> +class SensorService() : LifecycleService() {
please inject here your sensor

2022-03-22 06:59 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/db/FluctuationDataBase.kt
> +abstract class FluctuationDataBase : RoomDatabase() {
done

2022-03-22 07:00 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/services/CensorService.kt
> +    inner class CensorServiceBinder : Binder() {
done

2022-03-22 07:02 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +                        value[0],
fixed

2022-03-22 07:02 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +                    trySend(list)
done

2022-03-22 07:04 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/dao/IFluctuationDao.kt
> +    suspend fun addGravityFluctuationsRecord(records: List<FluctuationEntity>)
Added new delete function in dao which I'll triger every time record starts

2022-03-22 07:05 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/datasouce/GravitySensorDataSource.kt
> +        val list: MutableList<GravityValue> = mutableListOf()
done

2022-03-22 07:54 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/services/CensorService.kt
> +    fun startGravityCensorObserving() = lifecycleScope.launch(Dispatchers.Default) {
done

2022-03-24 10:04 UTC, AlexeyKolosov approved these changes

2022-03-24 10:04 UTC, merged