Gravity UI
EntyR/RandomNumberDB pull request #46
Opened 2022-03-30 12:41 UTC by EntyR

2022-03-30 12:57 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/viewmodel/GravityViewModel.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
please remove conditions, as discussed

2022-03-30 12:57 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/services/SensorService.kt
>          super.onStartCommand(intent, flags, startId)
also, it seems to me, that it is better to reset database data in `onStartCommand` instead of resetting it in `onCreate`

2022-04-04 05:55 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +                            viewModel.switchRecordState()
I think it it a strange logics. Currently it stops after 10 records, but we have discussed, that it should display last 10 records at every time, so it should not stop collection. Only user can stop collection.

2022-04-04 05:55 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +                        if (list.size >= 10 && viewModel.isNewSensorRecord) {
also please put all comprehensive logics to view model

2022-04-04 05:55 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +        viewModel.getSensorData()
why do you call this

2022-04-04 05:55 UTC, AlexeyKolosov commented on app/src/main/res/values/strings.xml
> +    <string name="start_recording">Start recording</string>
please don't forget to add "stop" text

2022-04-04 06:14 UTC, AlexeyKolosov requested changes

2022-04-04 06:14 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +            binding.chScatterChart.data = data
[important]  I can't see that data is displayed according to timestamps, currently timestamps are not used

2022-04-04 08:06 UTC, EntyR commented on app/src/main/res/values/strings.xml
> +    <string name="start_recording">Start recording</string>
yep, completely forgot about it, added

2022-04-04 08:06 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +        viewModel.getSensorData()
deleted

2022-04-04 08:07 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +                        if (list.size >= 10 && viewModel.isNewSensorRecord) {
done

2022-04-04 08:08 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/ui/fragments/GravityChart.kt
> +                            viewModel.switchRecordState()
changed it, so now last 10 records is shown

2022-04-04 08:08 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/services/SensorService.kt
>          super.onStartCommand(intent, flags, startId)
done

2022-04-04 11:23 UTC, AlexeyKolosov commented on app/src/test/java/com/harman/roomdbapp/SensorServiceTest.kt
> +    private fun setStaticFieldViaReflection(field: Field, value: Any) {
I think, you can move this method into separate object (to use in other test classes). something like ReflectionUtils.kt

2022-04-05 06:53 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/TimeUtil.kt
> +object TimeUtil {
please add tests for this object, also actually you can put these methods right in TimeUtil.kt without creating an object

2022-04-05 10:41 UTC, EntyR commented on app/src/test/java/com/harman/roomdbapp/SensorServiceTest.kt
> +    private fun setStaticFieldViaReflection(field: Field, value: Any) {
done

2022-04-05 10:41 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/TimeUtil.kt
> +object TimeUtil {
done

2022-04-05 10:46 UTC, AlexeyKolosov approved these changes

2022-04-05 10:59 UTC, merged