Add worker document interaction
EntyR/RandomNumberDB pull request #55
Opened 2022-04-07 06:08 UTC by EntyR

2022-04-07 08:07 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        return withContext(Dispatchers.IO) {
lets remove withContext, because Worker already works in background thread, so this call will be performed synchronously in a background thread

2022-04-07 08:07 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +    private fun addNewEntry(filename: String, csvString: String): Boolean {
not sure that this method will be used. I think, every 5 minutes worker can create the new file, if there is the new data in the db, so worker will not wait for all new data samples, and will write all new items to this moment

2022-04-07 11:44 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val value = db.getGravityFluctuationsRecord().asLiveData().value?.map {
please don't use liveData anywhere except objects with lifecycle. Here you can use getGravityFluctuationsRecord().first()

2022-04-07 11:44 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        if (value.containsAll(currentList))
lets don't keep the list as a variable, as it can be very big. Please cache max timestamp from which you should copy data next time. For caching you can use either database or https://developer.android.com/reference/android/content/SharedPreferences

2022-04-08 15:55 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +                "${UUID.randomUUID()}.csv",
lets use last timestamp instead of uuid

2022-04-08 15:55 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val lastItem = value.last().toGravityRecord().convertToCsv()
I think, you need to put into the new csv all items, which have not been saved since previous backup

2022-04-08 15:55 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val lastItem = value.last().toGravityRecord().convertToCsv()
![image](https://user-images.githubusercontent.com/48712070/162478635-b3acf6be-738b-402a-a3aa-a133af8ffe5e.png)

2022-04-08 16:04 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/MemoryUtil.kt
> +            DocumentEntry(it.name, timeStamp)
See other comments, and I think you won't need DocumentEntry at all, just list of file names

2022-04-08 16:04 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/MemoryUtil.kt
> +    fun getLastRecord(): String {
It is better to keep this method in repositories

2022-04-08 16:04 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/MemoryUtil.kt
> +    fun getLastRecord(): String {
also move "set" method there

2022-04-08 16:04 UTC, AlexeyKolosov commented on domain/src/main/java/com/harman/roomdbapp/domain/model/DocumentEntry.kt
> +data class DocumentEntry(
won't be needed if you make fileName="data-$LastTimestamp.csv", so you can easy get timestamp

2022-04-11 07:46 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        return withContext(Dispatchers.IO) {
done

2022-04-11 07:47 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val value = db.getGravityFluctuationsRecord().asLiveData().value?.map {
done

2022-04-11 12:45 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        if (value.containsAll(currentList))
done

2022-04-11 12:45 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +                "${UUID.randomUUID()}.csv",
done

2022-04-11 12:45 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val lastItem = value.last().toGravityRecord().convertToCsv()
done

2022-04-11 12:51 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +    private fun addNewEntry(filename: String, csvString: String): Boolean {
done

2022-04-11 13:45 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/MemoryUtil.kt
> +    fun getLastRecord(): String {
done

2022-04-11 13:45 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/MemoryUtil.kt
> +            DocumentEntry(it.name, timeStamp)
yes. deleted it

2022-04-11 13:45 UTC, EntyR commented on domain/src/main/java/com/harman/roomdbapp/domain/model/DocumentEntry.kt
> +data class DocumentEntry(
deleted

2022-04-11 14:03 UTC, AlexeyKolosov requested changes

2022-04-11 14:03 UTC, AlexeyKolosov commented on domain/src/main/java/com/harman/roomdbapp/domain/use_cases/GravityDocumentsUseCase.kt
> +    fun storeLastRecord(lastRecord: String) {
its is better to have `fun setLastBackupRecordTimestamp(lastRecord: Long) `

2022-04-11 14:03 UTC, AlexeyKolosov commented on domain/src/main/java/com/harman/roomdbapp/domain/use_cases/GravityDocumentsUseCase.kt
> +    fun getLastRecord(): String = repository.getLastRecord()
its is better to have `fun getLastBackupRecordTimestamp(): Long `

2022-04-11 14:03 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val value = fluctuationUseCase.getFluctuationRecords().first()
`val records = fluctuationUseCase.getFluctuationRecords().first()`

2022-04-11 14:03 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        documentUseCase.storeLastRecord(value.last().convertToCsv())
`setLastBackupRecordTimestamp(records.sortedBy {it. timestamp}.last().timestamp)`

2022-04-11 14:03 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +            "${value.last().timestamp}.csv", value
`documentUseCase.addNewGravityDocument(records)` you can create name right in this method, based on last timestamp

2022-04-11 14:03 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +                addNewRecords(value)
```
val newRecordsToSave = records.filter {it.timestamp > lastBackupRecordTimestamp}
addNewRecords(newRecordsToSave )
```

2022-04-11 14:03 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/repository/DocumentRepository.kt
> +    override fun addNewCsvFile(filename: String, list: List<GravityRecord>): Boolean {
create file name here based on the highest timestamp

2022-04-11 14:03 UTC, AlexeyKolosov commented on data/src/main/java/com/harman/roomdbapp/data/repository/DocumentRepository.kt
> +        val sharedPref =
It seems to me that sharedPref could be as private field of this repository

2022-04-11 14:03 UTC, AlexeyKolosov commented on app/src/main/AndroidManifest.xml
> +        <provider
please describe why do you use this?

2022-04-11 14:28 UTC, EntyR commented on app/src/main/AndroidManifest.xml
> +        <provider
Basicaly to prevent Android initializing its default WorkManagerFactory, it said to do so in koin documentation
https://insert-koin.io/docs/reference/koin-android/workmanager/

2022-04-11 14:32 UTC, EntyR commented on app/src/main/AndroidManifest.xml
> +        <provider
Tryed to run without it. app crashed

2022-04-11 14:33 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/repository/DocumentRepository.kt
> +        val sharedPref =
done

2022-04-11 14:33 UTC, EntyR commented on data/src/main/java/com/harman/roomdbapp/data/repository/DocumentRepository.kt
> +    override fun addNewCsvFile(filename: String, list: List<GravityRecord>): Boolean {
done

2022-04-11 14:33 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +                addNewRecords(value)
changed it

2022-04-11 14:34 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +            "${value.last().timestamp}.csv", value
yep. done

2022-04-11 14:51 UTC, EntyR commented on domain/src/main/java/com/harman/roomdbapp/domain/use_cases/GravityDocumentsUseCase.kt
> +    fun storeLastRecord(lastRecord: String) {
done

2022-04-11 14:51 UTC, EntyR commented on domain/src/main/java/com/harman/roomdbapp/domain/use_cases/GravityDocumentsUseCase.kt
> +    fun getLastRecord(): String = repository.getLastRecord()
done

2022-04-11 14:52 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        val value = fluctuationUseCase.getFluctuationRecords().first()
changed

2022-04-11 14:52 UTC, EntyR commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        documentUseCase.storeLastRecord(value.last().convertToCsv())
done

2022-04-12 07:48 UTC, AlexeyKolosov commented on app/src/main/java/com/harman/roomdbapp/app/other/worker/DocumentCoroutineWorker.kt
> +        return if (lastItemCsv == lastRecordCsv) {
I think, you don't need such complicated logics, maybe this will be more readable
```
        val lastTimestamp = documentUseCase.getLastBackupRecordTimestamp()
        records.filter { it.timestamp > lastTimestamp }.let{
                if(!it.isNullOrEmpty()){
                        addNewRecords(it)
                }
        }
        return Result.success()
```

2022-04-12 07:53 UTC, AlexeyKolosov commented on app/src/main/AndroidManifest.xml
> +        <provider
Ok, I will check it too after all functionality will be ready, thanks

2022-04-12 07:59 UTC, AlexeyKolosov approved these changes

2022-04-12 08:00 UTC, merged